
# 20251007 : Updated hide_when_typing and theme (using ozsh)
# 20250706 : Updated for MacOS
# 20250604 : Added auto-imported, general section, blur
# 20240808 : By Sergio

# Sources
# https://alacritty.org/config-alacritty.html


# Alacritty config file
# $HOME/.config/alacritty/alacritty.toml



[general]
live_config_reload = true
#import = [ "~/.config/alacritty/themes/themes/Cobalt2.toml" ]

[window]
dimensions = { columns = 120, lines = 50 }
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Full"
#decorations_theme_variant = "Dark"
opacity = 0.7
blur = true
dynamic_title = true

option_as_alt = "OnlyRight"

[font]
size = 14.0

normal = { family = "NotoMono Nerd Font"  }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[bell]
animation = "EaseOutCubic"
duration = 1


[selection]
save_to_clipboard = true


[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true
blink_interval = 600
blink_timeout = 0
thickness = 0.4

[mouse]
hide_when_typing = false
